# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0bpriemman.v1\x1a\x0c\x63ommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1f\n\x0eSendOtpRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"M\n\x0fSendOtpResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10\x63ooldown_seconds\x18\x03 \x01(\x05\".\n\x10VerifyOtpRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"?\n\x11VerifyOtpResponse\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x13\n\x0bis_new_user\x18\x02 \x01(\x08\"`\n\x14OAuthCallbackRequest\x12+\n\x08provider\x18\x01 \x01(\x0e\x32\x19.priemman.v1.AuthProvider\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"C\n\x15OAuthCallbackResponse\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x13\n\x0bis_new_user\x18\x02 \x01(\x08\"p\n\x07Session\x12\r\n\x05token\x18\x01 \x01(\t\x12&\n\x07user_id\x18\x02 \x01(\x0b\x32\x15.priemman.v1.ObjectId\x12.\n\nexpires_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"&\n\rLogoutRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"!\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*z\n\x0c\x41uthProvider\x12\x1d\n\x19\x41UTH_PROVIDER_UNSPECIFIED\x10\x00\x12\x17\n\x13\x41UTH_PROVIDER_EMAIL\x10\x01\x12\x18\n\x14\x41UTH_PROVIDER_GOOGLE\x10\x02\x12\x18\n\x14\x41UTH_PROVIDER_GITHUB\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHPROVIDER._serialized_start=655
  _AUTHPROVIDER._serialized_end=777
  _SENDOTPREQUEST._serialized_start=74
  _SENDOTPREQUEST._serialized_end=105
  _SENDOTPRESPONSE._serialized_start=107
  _SENDOTPRESPONSE._serialized_end=184
  _VERIFYOTPREQUEST._serialized_start=186
  _VERIFYOTPREQUEST._serialized_end=232
  _VERIFYOTPRESPONSE._serialized_start=234
  _VERIFYOTPRESPONSE._serialized_end=297
  _OAUTHCALLBACKREQUEST._serialized_start=299
  _OAUTHCALLBACKREQUEST._serialized_end=395
  _OAUTHCALLBACKRESPONSE._serialized_start=397
  _OAUTHCALLBACKRESPONSE._serialized_end=464
  _SESSION._serialized_start=466
  _SESSION._serialized_end=578
  _LOGOUTREQUEST._serialized_start=580
  _LOGOUTREQUEST._serialized_end=618
  _LOGOUTRESPONSE._serialized_start=620
  _LOGOUTRESPONSE._serialized_end=653
# @@protoc_insertion_point(module_scope)
