# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0bpriemman.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n\x08ObjectId\x12\r\n\x05value\x18\x01 \x01(\t\")\n\x08Location\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\"\x8b\x01\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x30\n\x04meta\x18\x03 \x03(\x0b\x32\".priemman.v1.ErrorDetail.MetaEntry\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"}\n\x06Result\x12\x10\n\x08is_error\x18\x01 \x01(\x08\x12\x11\n\thas_value\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12.\n\x0c\x65rror_detail\x18\x05 \x01(\x0b\x32\x18.priemman.v1.ErrorDetailb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ERRORDETAIL_METAENTRY._options = None
  _ERRORDETAIL_METAENTRY._serialized_options = b'8\001'
  _OBJECTID._serialized_start=62
  _OBJECTID._serialized_end=87
  _LOCATION._serialized_start=89
  _LOCATION._serialized_end=130
  _ERRORDETAIL._serialized_start=133
  _ERRORDETAIL._serialized_end=272
  _ERRORDETAIL_METAENTRY._serialized_start=229
  _ERRORDETAIL_METAENTRY._serialized_end=272
  _RESULT._serialized_start=274
  _RESULT._serialized_end=399
# @@protoc_insertion_point(module_scope)
