# Database
db-host:
db-port:
db-user:
db-password:
db-name:
db-pool-size: 15

# SMTP
smtp-host:
smtp-port:
smtp-email:
smtp-password:

# OAuth
google-redirect-url:
google-client-id:
google-client-secret:

github-redirect-url:
github-client-id:
github-client-secret:

# CORS - INI ARRAY, lebih baik di config_vars
cors-allowed-origins:
    - http://localhost:3000
    - http://localhost:5173

# Server
server-port: 8080
worker-threads: 4
log-level: error
