cloudinary-cloud-name:
cloudinary-api-key:
cloudinary-api-secret:

base-domain: 'localhost'

# SMTP
smtp-host:
smtp-port:
smtp-email:
smtp-password:

# OAuth
google-redirect-url:
google-client-id:
google-client-secret:

github-redirect-url:
github-client-id:
github-client-secret:


# Server
server-port: 8080
worker-threads: 4
log-level: error

# Frontend dashboard (redirect setelah login, sesuai role)
dashboard-url: 'http://localhost:3000/dashboard'
dashboard-creator-url: 'http://localhost:3000/dashboard-creator'
dashboard-admin-url: 'http://localhost:3000/dashboard-admin'

# Frontend server
favicon-path: '../static/favicon.ico'
