// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_auth_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_auth_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_auth_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_auth_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_auth_2eproto;
namespace priemman {
namespace v1 {
class LogoutRequest;
struct LogoutRequestDefaultTypeInternal;
extern LogoutRequestDefaultTypeInternal _LogoutRequest_default_instance_;
class LogoutResponse;
struct LogoutResponseDefaultTypeInternal;
extern LogoutResponseDefaultTypeInternal _LogoutResponse_default_instance_;
class OAuthCallbackRequest;
struct OAuthCallbackRequestDefaultTypeInternal;
extern OAuthCallbackRequestDefaultTypeInternal _OAuthCallbackRequest_default_instance_;
class OAuthCallbackResponse;
struct OAuthCallbackResponseDefaultTypeInternal;
extern OAuthCallbackResponseDefaultTypeInternal _OAuthCallbackResponse_default_instance_;
class SendOtpRequest;
struct SendOtpRequestDefaultTypeInternal;
extern SendOtpRequestDefaultTypeInternal _SendOtpRequest_default_instance_;
class SendOtpResponse;
struct SendOtpResponseDefaultTypeInternal;
extern SendOtpResponseDefaultTypeInternal _SendOtpResponse_default_instance_;
class Session;
struct SessionDefaultTypeInternal;
extern SessionDefaultTypeInternal _Session_default_instance_;
class VerifyOtpRequest;
struct VerifyOtpRequestDefaultTypeInternal;
extern VerifyOtpRequestDefaultTypeInternal _VerifyOtpRequest_default_instance_;
class VerifyOtpResponse;
struct VerifyOtpResponseDefaultTypeInternal;
extern VerifyOtpResponseDefaultTypeInternal _VerifyOtpResponse_default_instance_;
}  // namespace v1
}  // namespace priemman
PROTOBUF_NAMESPACE_OPEN
template<> ::priemman::v1::LogoutRequest* Arena::CreateMaybeMessage<::priemman::v1::LogoutRequest>(Arena*);
template<> ::priemman::v1::LogoutResponse* Arena::CreateMaybeMessage<::priemman::v1::LogoutResponse>(Arena*);
template<> ::priemman::v1::OAuthCallbackRequest* Arena::CreateMaybeMessage<::priemman::v1::OAuthCallbackRequest>(Arena*);
template<> ::priemman::v1::OAuthCallbackResponse* Arena::CreateMaybeMessage<::priemman::v1::OAuthCallbackResponse>(Arena*);
template<> ::priemman::v1::SendOtpRequest* Arena::CreateMaybeMessage<::priemman::v1::SendOtpRequest>(Arena*);
template<> ::priemman::v1::SendOtpResponse* Arena::CreateMaybeMessage<::priemman::v1::SendOtpResponse>(Arena*);
template<> ::priemman::v1::Session* Arena::CreateMaybeMessage<::priemman::v1::Session>(Arena*);
template<> ::priemman::v1::VerifyOtpRequest* Arena::CreateMaybeMessage<::priemman::v1::VerifyOtpRequest>(Arena*);
template<> ::priemman::v1::VerifyOtpResponse* Arena::CreateMaybeMessage<::priemman::v1::VerifyOtpResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace priemman {
namespace v1 {

enum AuthProvider : int {
  AUTH_PROVIDER_UNSPECIFIED = 0,
  AUTH_PROVIDER_EMAIL = 1,
  AUTH_PROVIDER_GOOGLE = 2,
  AUTH_PROVIDER_GITHUB = 3,
  AuthProvider_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AuthProvider_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AuthProvider_IsValid(int value);
constexpr AuthProvider AuthProvider_MIN = AUTH_PROVIDER_UNSPECIFIED;
constexpr AuthProvider AuthProvider_MAX = AUTH_PROVIDER_GITHUB;
constexpr int AuthProvider_ARRAYSIZE = AuthProvider_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AuthProvider_descriptor();
template<typename T>
inline const std::string& AuthProvider_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AuthProvider>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AuthProvider_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AuthProvider_descriptor(), enum_t_value);
}
inline bool AuthProvider_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AuthProvider* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AuthProvider>(
    AuthProvider_descriptor(), name, value);
}
// ===================================================================

class SendOtpRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.SendOtpRequest) */ {
 public:
  inline SendOtpRequest() : SendOtpRequest(nullptr) {}
  ~SendOtpRequest() override;
  explicit PROTOBUF_CONSTEXPR SendOtpRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendOtpRequest(const SendOtpRequest& from);
  SendOtpRequest(SendOtpRequest&& from) noexcept
    : SendOtpRequest() {
    *this = ::std::move(from);
  }

  inline SendOtpRequest& operator=(const SendOtpRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendOtpRequest& operator=(SendOtpRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendOtpRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendOtpRequest* internal_default_instance() {
    return reinterpret_cast<const SendOtpRequest*>(
               &_SendOtpRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SendOtpRequest& a, SendOtpRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SendOtpRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendOtpRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendOtpRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendOtpRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendOtpRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendOtpRequest& from) {
    SendOtpRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendOtpRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.SendOtpRequest";
  }
  protected:
  explicit SendOtpRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEmailFieldNumber = 1,
  };
  // string email = 1;
  void clear_email();
  const std::string& email() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_email(ArgT0&& arg0, ArgT... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // @@protoc_insertion_point(class_scope:priemman.v1.SendOtpRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class SendOtpResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.SendOtpResponse) */ {
 public:
  inline SendOtpResponse() : SendOtpResponse(nullptr) {}
  ~SendOtpResponse() override;
  explicit PROTOBUF_CONSTEXPR SendOtpResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SendOtpResponse(const SendOtpResponse& from);
  SendOtpResponse(SendOtpResponse&& from) noexcept
    : SendOtpResponse() {
    *this = ::std::move(from);
  }

  inline SendOtpResponse& operator=(const SendOtpResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SendOtpResponse& operator=(SendOtpResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SendOtpResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SendOtpResponse* internal_default_instance() {
    return reinterpret_cast<const SendOtpResponse*>(
               &_SendOtpResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SendOtpResponse& a, SendOtpResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SendOtpResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SendOtpResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SendOtpResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SendOtpResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SendOtpResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SendOtpResponse& from) {
    SendOtpResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SendOtpResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.SendOtpResponse";
  }
  protected:
  explicit SendOtpResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
    kCooldownSecondsFieldNumber = 3,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 cooldown_seconds = 3;
  void clear_cooldown_seconds();
  int32_t cooldown_seconds() const;
  void set_cooldown_seconds(int32_t value);
  private:
  int32_t _internal_cooldown_seconds() const;
  void _internal_set_cooldown_seconds(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:priemman.v1.SendOtpResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    bool success_;
    int32_t cooldown_seconds_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class VerifyOtpRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.VerifyOtpRequest) */ {
 public:
  inline VerifyOtpRequest() : VerifyOtpRequest(nullptr) {}
  ~VerifyOtpRequest() override;
  explicit PROTOBUF_CONSTEXPR VerifyOtpRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VerifyOtpRequest(const VerifyOtpRequest& from);
  VerifyOtpRequest(VerifyOtpRequest&& from) noexcept
    : VerifyOtpRequest() {
    *this = ::std::move(from);
  }

  inline VerifyOtpRequest& operator=(const VerifyOtpRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifyOtpRequest& operator=(VerifyOtpRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyOtpRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifyOtpRequest* internal_default_instance() {
    return reinterpret_cast<const VerifyOtpRequest*>(
               &_VerifyOtpRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(VerifyOtpRequest& a, VerifyOtpRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(VerifyOtpRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyOtpRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyOtpRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VerifyOtpRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VerifyOtpRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VerifyOtpRequest& from) {
    VerifyOtpRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VerifyOtpRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.VerifyOtpRequest";
  }
  protected:
  explicit VerifyOtpRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEmailFieldNumber = 1,
    kOtpFieldNumber = 2,
  };
  // string email = 1;
  void clear_email();
  const std::string& email() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_email(ArgT0&& arg0, ArgT... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // string otp = 2;
  void clear_otp();
  const std::string& otp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_otp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_otp();
  PROTOBUF_NODISCARD std::string* release_otp();
  void set_allocated_otp(std::string* otp);
  private:
  const std::string& _internal_otp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_otp(const std::string& value);
  std::string* _internal_mutable_otp();
  public:

  // @@protoc_insertion_point(class_scope:priemman.v1.VerifyOtpRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr otp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class VerifyOtpResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.VerifyOtpResponse) */ {
 public:
  inline VerifyOtpResponse() : VerifyOtpResponse(nullptr) {}
  ~VerifyOtpResponse() override;
  explicit PROTOBUF_CONSTEXPR VerifyOtpResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VerifyOtpResponse(const VerifyOtpResponse& from);
  VerifyOtpResponse(VerifyOtpResponse&& from) noexcept
    : VerifyOtpResponse() {
    *this = ::std::move(from);
  }

  inline VerifyOtpResponse& operator=(const VerifyOtpResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline VerifyOtpResponse& operator=(VerifyOtpResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VerifyOtpResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const VerifyOtpResponse* internal_default_instance() {
    return reinterpret_cast<const VerifyOtpResponse*>(
               &_VerifyOtpResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(VerifyOtpResponse& a, VerifyOtpResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(VerifyOtpResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VerifyOtpResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VerifyOtpResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VerifyOtpResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VerifyOtpResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VerifyOtpResponse& from) {
    VerifyOtpResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VerifyOtpResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.VerifyOtpResponse";
  }
  protected:
  explicit VerifyOtpResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionTokenFieldNumber = 1,
    kIsNewUserFieldNumber = 2,
  };
  // string session_token = 1;
  void clear_session_token();
  const std::string& session_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_token();
  PROTOBUF_NODISCARD std::string* release_session_token();
  void set_allocated_session_token(std::string* session_token);
  private:
  const std::string& _internal_session_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_token(const std::string& value);
  std::string* _internal_mutable_session_token();
  public:

  // bool is_new_user = 2;
  void clear_is_new_user();
  bool is_new_user() const;
  void set_is_new_user(bool value);
  private:
  bool _internal_is_new_user() const;
  void _internal_set_is_new_user(bool value);
  public:

  // @@protoc_insertion_point(class_scope:priemman.v1.VerifyOtpResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_token_;
    bool is_new_user_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class OAuthCallbackRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.OAuthCallbackRequest) */ {
 public:
  inline OAuthCallbackRequest() : OAuthCallbackRequest(nullptr) {}
  ~OAuthCallbackRequest() override;
  explicit PROTOBUF_CONSTEXPR OAuthCallbackRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OAuthCallbackRequest(const OAuthCallbackRequest& from);
  OAuthCallbackRequest(OAuthCallbackRequest&& from) noexcept
    : OAuthCallbackRequest() {
    *this = ::std::move(from);
  }

  inline OAuthCallbackRequest& operator=(const OAuthCallbackRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OAuthCallbackRequest& operator=(OAuthCallbackRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OAuthCallbackRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const OAuthCallbackRequest* internal_default_instance() {
    return reinterpret_cast<const OAuthCallbackRequest*>(
               &_OAuthCallbackRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(OAuthCallbackRequest& a, OAuthCallbackRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(OAuthCallbackRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OAuthCallbackRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OAuthCallbackRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OAuthCallbackRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OAuthCallbackRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OAuthCallbackRequest& from) {
    OAuthCallbackRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OAuthCallbackRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.OAuthCallbackRequest";
  }
  protected:
  explicit OAuthCallbackRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCodeFieldNumber = 2,
    kStateFieldNumber = 3,
    kProviderFieldNumber = 1,
  };
  // string code = 2;
  void clear_code();
  const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // string state = 3;
  void clear_state();
  const std::string& state() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_state(ArgT0&& arg0, ArgT... args);
  std::string* mutable_state();
  PROTOBUF_NODISCARD std::string* release_state();
  void set_allocated_state(std::string* state);
  private:
  const std::string& _internal_state() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_state(const std::string& value);
  std::string* _internal_mutable_state();
  public:

  // .priemman.v1.AuthProvider provider = 1;
  void clear_provider();
  ::priemman::v1::AuthProvider provider() const;
  void set_provider(::priemman::v1::AuthProvider value);
  private:
  ::priemman::v1::AuthProvider _internal_provider() const;
  void _internal_set_provider(::priemman::v1::AuthProvider value);
  public:

  // @@protoc_insertion_point(class_scope:priemman.v1.OAuthCallbackRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr state_;
    int provider_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class OAuthCallbackResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.OAuthCallbackResponse) */ {
 public:
  inline OAuthCallbackResponse() : OAuthCallbackResponse(nullptr) {}
  ~OAuthCallbackResponse() override;
  explicit PROTOBUF_CONSTEXPR OAuthCallbackResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OAuthCallbackResponse(const OAuthCallbackResponse& from);
  OAuthCallbackResponse(OAuthCallbackResponse&& from) noexcept
    : OAuthCallbackResponse() {
    *this = ::std::move(from);
  }

  inline OAuthCallbackResponse& operator=(const OAuthCallbackResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline OAuthCallbackResponse& operator=(OAuthCallbackResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OAuthCallbackResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const OAuthCallbackResponse* internal_default_instance() {
    return reinterpret_cast<const OAuthCallbackResponse*>(
               &_OAuthCallbackResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(OAuthCallbackResponse& a, OAuthCallbackResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(OAuthCallbackResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OAuthCallbackResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OAuthCallbackResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OAuthCallbackResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OAuthCallbackResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OAuthCallbackResponse& from) {
    OAuthCallbackResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OAuthCallbackResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.OAuthCallbackResponse";
  }
  protected:
  explicit OAuthCallbackResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionTokenFieldNumber = 1,
    kIsNewUserFieldNumber = 2,
  };
  // string session_token = 1;
  void clear_session_token();
  const std::string& session_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_token();
  PROTOBUF_NODISCARD std::string* release_session_token();
  void set_allocated_session_token(std::string* session_token);
  private:
  const std::string& _internal_session_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_token(const std::string& value);
  std::string* _internal_mutable_session_token();
  public:

  // bool is_new_user = 2;
  void clear_is_new_user();
  bool is_new_user() const;
  void set_is_new_user(bool value);
  private:
  bool _internal_is_new_user() const;
  void _internal_set_is_new_user(bool value);
  public:

  // @@protoc_insertion_point(class_scope:priemman.v1.OAuthCallbackResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_token_;
    bool is_new_user_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class Session final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.Session) */ {
 public:
  inline Session() : Session(nullptr) {}
  ~Session() override;
  explicit PROTOBUF_CONSTEXPR Session(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Session(const Session& from);
  Session(Session&& from) noexcept
    : Session() {
    *this = ::std::move(from);
  }

  inline Session& operator=(const Session& from) {
    CopyFrom(from);
    return *this;
  }
  inline Session& operator=(Session&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Session& default_instance() {
    return *internal_default_instance();
  }
  static inline const Session* internal_default_instance() {
    return reinterpret_cast<const Session*>(
               &_Session_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Session& a, Session& b) {
    a.Swap(&b);
  }
  inline void Swap(Session* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Session* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Session* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Session>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Session& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Session& from) {
    Session::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Session* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.Session";
  }
  protected:
  explicit Session(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kExpiresAtFieldNumber = 3,
  };
  // string token = 1;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // .priemman.v1.ObjectId user_id = 2;
  bool has_user_id() const;
  private:
  bool _internal_has_user_id() const;
  public:
  void clear_user_id();
  const ::priemman::v1::ObjectId& user_id() const;
  PROTOBUF_NODISCARD ::priemman::v1::ObjectId* release_user_id();
  ::priemman::v1::ObjectId* mutable_user_id();
  void set_allocated_user_id(::priemman::v1::ObjectId* user_id);
  private:
  const ::priemman::v1::ObjectId& _internal_user_id() const;
  ::priemman::v1::ObjectId* _internal_mutable_user_id();
  public:
  void unsafe_arena_set_allocated_user_id(
      ::priemman::v1::ObjectId* user_id);
  ::priemman::v1::ObjectId* unsafe_arena_release_user_id();

  // .google.protobuf.Timestamp expires_at = 3;
  bool has_expires_at() const;
  private:
  bool _internal_has_expires_at() const;
  public:
  void clear_expires_at();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& expires_at() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_expires_at();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_expires_at();
  void set_allocated_expires_at(::PROTOBUF_NAMESPACE_ID::Timestamp* expires_at);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_expires_at() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_expires_at();
  public:
  void unsafe_arena_set_allocated_expires_at(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* expires_at);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_expires_at();

  // @@protoc_insertion_point(class_scope:priemman.v1.Session)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
    ::priemman::v1::ObjectId* user_id_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* expires_at_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class LogoutRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.LogoutRequest) */ {
 public:
  inline LogoutRequest() : LogoutRequest(nullptr) {}
  ~LogoutRequest() override;
  explicit PROTOBUF_CONSTEXPR LogoutRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogoutRequest(const LogoutRequest& from);
  LogoutRequest(LogoutRequest&& from) noexcept
    : LogoutRequest() {
    *this = ::std::move(from);
  }

  inline LogoutRequest& operator=(const LogoutRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogoutRequest& operator=(LogoutRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogoutRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogoutRequest* internal_default_instance() {
    return reinterpret_cast<const LogoutRequest*>(
               &_LogoutRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(LogoutRequest& a, LogoutRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LogoutRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogoutRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogoutRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogoutRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogoutRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogoutRequest& from) {
    LogoutRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogoutRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.LogoutRequest";
  }
  protected:
  explicit LogoutRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionTokenFieldNumber = 1,
  };
  // string session_token = 1;
  void clear_session_token();
  const std::string& session_token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_token();
  PROTOBUF_NODISCARD std::string* release_session_token();
  void set_allocated_session_token(std::string* session_token);
  private:
  const std::string& _internal_session_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_token(const std::string& value);
  std::string* _internal_mutable_session_token();
  public:

  // @@protoc_insertion_point(class_scope:priemman.v1.LogoutRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_token_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class LogoutResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:priemman.v1.LogoutResponse) */ {
 public:
  inline LogoutResponse() : LogoutResponse(nullptr) {}
  ~LogoutResponse() override;
  explicit PROTOBUF_CONSTEXPR LogoutResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogoutResponse(const LogoutResponse& from);
  LogoutResponse(LogoutResponse&& from) noexcept
    : LogoutResponse() {
    *this = ::std::move(from);
  }

  inline LogoutResponse& operator=(const LogoutResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogoutResponse& operator=(LogoutResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogoutResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogoutResponse* internal_default_instance() {
    return reinterpret_cast<const LogoutResponse*>(
               &_LogoutResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(LogoutResponse& a, LogoutResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LogoutResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogoutResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogoutResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogoutResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogoutResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogoutResponse& from) {
    LogoutResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogoutResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "priemman.v1.LogoutResponse";
  }
  protected:
  explicit LogoutResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:priemman.v1.LogoutResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SendOtpRequest

// string email = 1;
inline void SendOtpRequest::clear_email() {
  _impl_.email_.ClearToEmpty();
}
inline const std::string& SendOtpRequest::email() const {
  // @@protoc_insertion_point(field_get:priemman.v1.SendOtpRequest.email)
  return _internal_email();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SendOtpRequest::set_email(ArgT0&& arg0, ArgT... args) {
 
 _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.SendOtpRequest.email)
}
inline std::string* SendOtpRequest::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:priemman.v1.SendOtpRequest.email)
  return _s;
}
inline const std::string& SendOtpRequest::_internal_email() const {
  return _impl_.email_.Get();
}
inline void SendOtpRequest::_internal_set_email(const std::string& value) {
  
  _impl_.email_.Set(value, GetArenaForAllocation());
}
inline std::string* SendOtpRequest::_internal_mutable_email() {
  
  return _impl_.email_.Mutable(GetArenaForAllocation());
}
inline std::string* SendOtpRequest::release_email() {
  // @@protoc_insertion_point(field_release:priemman.v1.SendOtpRequest.email)
  return _impl_.email_.Release();
}
inline void SendOtpRequest::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.SendOtpRequest.email)
}

// -------------------------------------------------------------------

// SendOtpResponse

// bool success = 1;
inline void SendOtpResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool SendOtpResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool SendOtpResponse::success() const {
  // @@protoc_insertion_point(field_get:priemman.v1.SendOtpResponse.success)
  return _internal_success();
}
inline void SendOtpResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void SendOtpResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:priemman.v1.SendOtpResponse.success)
}

// string message = 2;
inline void SendOtpResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& SendOtpResponse::message() const {
  // @@protoc_insertion_point(field_get:priemman.v1.SendOtpResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SendOtpResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.SendOtpResponse.message)
}
inline std::string* SendOtpResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:priemman.v1.SendOtpResponse.message)
  return _s;
}
inline const std::string& SendOtpResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void SendOtpResponse::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* SendOtpResponse::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* SendOtpResponse::release_message() {
  // @@protoc_insertion_point(field_release:priemman.v1.SendOtpResponse.message)
  return _impl_.message_.Release();
}
inline void SendOtpResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.SendOtpResponse.message)
}

// int32 cooldown_seconds = 3;
inline void SendOtpResponse::clear_cooldown_seconds() {
  _impl_.cooldown_seconds_ = 0;
}
inline int32_t SendOtpResponse::_internal_cooldown_seconds() const {
  return _impl_.cooldown_seconds_;
}
inline int32_t SendOtpResponse::cooldown_seconds() const {
  // @@protoc_insertion_point(field_get:priemman.v1.SendOtpResponse.cooldown_seconds)
  return _internal_cooldown_seconds();
}
inline void SendOtpResponse::_internal_set_cooldown_seconds(int32_t value) {
  
  _impl_.cooldown_seconds_ = value;
}
inline void SendOtpResponse::set_cooldown_seconds(int32_t value) {
  _internal_set_cooldown_seconds(value);
  // @@protoc_insertion_point(field_set:priemman.v1.SendOtpResponse.cooldown_seconds)
}

// -------------------------------------------------------------------

// VerifyOtpRequest

// string email = 1;
inline void VerifyOtpRequest::clear_email() {
  _impl_.email_.ClearToEmpty();
}
inline const std::string& VerifyOtpRequest::email() const {
  // @@protoc_insertion_point(field_get:priemman.v1.VerifyOtpRequest.email)
  return _internal_email();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VerifyOtpRequest::set_email(ArgT0&& arg0, ArgT... args) {
 
 _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.VerifyOtpRequest.email)
}
inline std::string* VerifyOtpRequest::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:priemman.v1.VerifyOtpRequest.email)
  return _s;
}
inline const std::string& VerifyOtpRequest::_internal_email() const {
  return _impl_.email_.Get();
}
inline void VerifyOtpRequest::_internal_set_email(const std::string& value) {
  
  _impl_.email_.Set(value, GetArenaForAllocation());
}
inline std::string* VerifyOtpRequest::_internal_mutable_email() {
  
  return _impl_.email_.Mutable(GetArenaForAllocation());
}
inline std::string* VerifyOtpRequest::release_email() {
  // @@protoc_insertion_point(field_release:priemman.v1.VerifyOtpRequest.email)
  return _impl_.email_.Release();
}
inline void VerifyOtpRequest::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.VerifyOtpRequest.email)
}

// string otp = 2;
inline void VerifyOtpRequest::clear_otp() {
  _impl_.otp_.ClearToEmpty();
}
inline const std::string& VerifyOtpRequest::otp() const {
  // @@protoc_insertion_point(field_get:priemman.v1.VerifyOtpRequest.otp)
  return _internal_otp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VerifyOtpRequest::set_otp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.otp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.VerifyOtpRequest.otp)
}
inline std::string* VerifyOtpRequest::mutable_otp() {
  std::string* _s = _internal_mutable_otp();
  // @@protoc_insertion_point(field_mutable:priemman.v1.VerifyOtpRequest.otp)
  return _s;
}
inline const std::string& VerifyOtpRequest::_internal_otp() const {
  return _impl_.otp_.Get();
}
inline void VerifyOtpRequest::_internal_set_otp(const std::string& value) {
  
  _impl_.otp_.Set(value, GetArenaForAllocation());
}
inline std::string* VerifyOtpRequest::_internal_mutable_otp() {
  
  return _impl_.otp_.Mutable(GetArenaForAllocation());
}
inline std::string* VerifyOtpRequest::release_otp() {
  // @@protoc_insertion_point(field_release:priemman.v1.VerifyOtpRequest.otp)
  return _impl_.otp_.Release();
}
inline void VerifyOtpRequest::set_allocated_otp(std::string* otp) {
  if (otp != nullptr) {
    
  } else {
    
  }
  _impl_.otp_.SetAllocated(otp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.otp_.IsDefault()) {
    _impl_.otp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.VerifyOtpRequest.otp)
}

// -------------------------------------------------------------------

// VerifyOtpResponse

// string session_token = 1;
inline void VerifyOtpResponse::clear_session_token() {
  _impl_.session_token_.ClearToEmpty();
}
inline const std::string& VerifyOtpResponse::session_token() const {
  // @@protoc_insertion_point(field_get:priemman.v1.VerifyOtpResponse.session_token)
  return _internal_session_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VerifyOtpResponse::set_session_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.VerifyOtpResponse.session_token)
}
inline std::string* VerifyOtpResponse::mutable_session_token() {
  std::string* _s = _internal_mutable_session_token();
  // @@protoc_insertion_point(field_mutable:priemman.v1.VerifyOtpResponse.session_token)
  return _s;
}
inline const std::string& VerifyOtpResponse::_internal_session_token() const {
  return _impl_.session_token_.Get();
}
inline void VerifyOtpResponse::_internal_set_session_token(const std::string& value) {
  
  _impl_.session_token_.Set(value, GetArenaForAllocation());
}
inline std::string* VerifyOtpResponse::_internal_mutable_session_token() {
  
  return _impl_.session_token_.Mutable(GetArenaForAllocation());
}
inline std::string* VerifyOtpResponse::release_session_token() {
  // @@protoc_insertion_point(field_release:priemman.v1.VerifyOtpResponse.session_token)
  return _impl_.session_token_.Release();
}
inline void VerifyOtpResponse::set_allocated_session_token(std::string* session_token) {
  if (session_token != nullptr) {
    
  } else {
    
  }
  _impl_.session_token_.SetAllocated(session_token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_token_.IsDefault()) {
    _impl_.session_token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.VerifyOtpResponse.session_token)
}

// bool is_new_user = 2;
inline void VerifyOtpResponse::clear_is_new_user() {
  _impl_.is_new_user_ = false;
}
inline bool VerifyOtpResponse::_internal_is_new_user() const {
  return _impl_.is_new_user_;
}
inline bool VerifyOtpResponse::is_new_user() const {
  // @@protoc_insertion_point(field_get:priemman.v1.VerifyOtpResponse.is_new_user)
  return _internal_is_new_user();
}
inline void VerifyOtpResponse::_internal_set_is_new_user(bool value) {
  
  _impl_.is_new_user_ = value;
}
inline void VerifyOtpResponse::set_is_new_user(bool value) {
  _internal_set_is_new_user(value);
  // @@protoc_insertion_point(field_set:priemman.v1.VerifyOtpResponse.is_new_user)
}

// -------------------------------------------------------------------

// OAuthCallbackRequest

// .priemman.v1.AuthProvider provider = 1;
inline void OAuthCallbackRequest::clear_provider() {
  _impl_.provider_ = 0;
}
inline ::priemman::v1::AuthProvider OAuthCallbackRequest::_internal_provider() const {
  return static_cast< ::priemman::v1::AuthProvider >(_impl_.provider_);
}
inline ::priemman::v1::AuthProvider OAuthCallbackRequest::provider() const {
  // @@protoc_insertion_point(field_get:priemman.v1.OAuthCallbackRequest.provider)
  return _internal_provider();
}
inline void OAuthCallbackRequest::_internal_set_provider(::priemman::v1::AuthProvider value) {
  
  _impl_.provider_ = value;
}
inline void OAuthCallbackRequest::set_provider(::priemman::v1::AuthProvider value) {
  _internal_set_provider(value);
  // @@protoc_insertion_point(field_set:priemman.v1.OAuthCallbackRequest.provider)
}

// string code = 2;
inline void OAuthCallbackRequest::clear_code() {
  _impl_.code_.ClearToEmpty();
}
inline const std::string& OAuthCallbackRequest::code() const {
  // @@protoc_insertion_point(field_get:priemman.v1.OAuthCallbackRequest.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OAuthCallbackRequest::set_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.OAuthCallbackRequest.code)
}
inline std::string* OAuthCallbackRequest::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:priemman.v1.OAuthCallbackRequest.code)
  return _s;
}
inline const std::string& OAuthCallbackRequest::_internal_code() const {
  return _impl_.code_.Get();
}
inline void OAuthCallbackRequest::_internal_set_code(const std::string& value) {
  
  _impl_.code_.Set(value, GetArenaForAllocation());
}
inline std::string* OAuthCallbackRequest::_internal_mutable_code() {
  
  return _impl_.code_.Mutable(GetArenaForAllocation());
}
inline std::string* OAuthCallbackRequest::release_code() {
  // @@protoc_insertion_point(field_release:priemman.v1.OAuthCallbackRequest.code)
  return _impl_.code_.Release();
}
inline void OAuthCallbackRequest::set_allocated_code(std::string* code) {
  if (code != nullptr) {
    
  } else {
    
  }
  _impl_.code_.SetAllocated(code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.OAuthCallbackRequest.code)
}

// string state = 3;
inline void OAuthCallbackRequest::clear_state() {
  _impl_.state_.ClearToEmpty();
}
inline const std::string& OAuthCallbackRequest::state() const {
  // @@protoc_insertion_point(field_get:priemman.v1.OAuthCallbackRequest.state)
  return _internal_state();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OAuthCallbackRequest::set_state(ArgT0&& arg0, ArgT... args) {
 
 _impl_.state_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.OAuthCallbackRequest.state)
}
inline std::string* OAuthCallbackRequest::mutable_state() {
  std::string* _s = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:priemman.v1.OAuthCallbackRequest.state)
  return _s;
}
inline const std::string& OAuthCallbackRequest::_internal_state() const {
  return _impl_.state_.Get();
}
inline void OAuthCallbackRequest::_internal_set_state(const std::string& value) {
  
  _impl_.state_.Set(value, GetArenaForAllocation());
}
inline std::string* OAuthCallbackRequest::_internal_mutable_state() {
  
  return _impl_.state_.Mutable(GetArenaForAllocation());
}
inline std::string* OAuthCallbackRequest::release_state() {
  // @@protoc_insertion_point(field_release:priemman.v1.OAuthCallbackRequest.state)
  return _impl_.state_.Release();
}
inline void OAuthCallbackRequest::set_allocated_state(std::string* state) {
  if (state != nullptr) {
    
  } else {
    
  }
  _impl_.state_.SetAllocated(state, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.state_.IsDefault()) {
    _impl_.state_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.OAuthCallbackRequest.state)
}

// -------------------------------------------------------------------

// OAuthCallbackResponse

// string session_token = 1;
inline void OAuthCallbackResponse::clear_session_token() {
  _impl_.session_token_.ClearToEmpty();
}
inline const std::string& OAuthCallbackResponse::session_token() const {
  // @@protoc_insertion_point(field_get:priemman.v1.OAuthCallbackResponse.session_token)
  return _internal_session_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OAuthCallbackResponse::set_session_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.OAuthCallbackResponse.session_token)
}
inline std::string* OAuthCallbackResponse::mutable_session_token() {
  std::string* _s = _internal_mutable_session_token();
  // @@protoc_insertion_point(field_mutable:priemman.v1.OAuthCallbackResponse.session_token)
  return _s;
}
inline const std::string& OAuthCallbackResponse::_internal_session_token() const {
  return _impl_.session_token_.Get();
}
inline void OAuthCallbackResponse::_internal_set_session_token(const std::string& value) {
  
  _impl_.session_token_.Set(value, GetArenaForAllocation());
}
inline std::string* OAuthCallbackResponse::_internal_mutable_session_token() {
  
  return _impl_.session_token_.Mutable(GetArenaForAllocation());
}
inline std::string* OAuthCallbackResponse::release_session_token() {
  // @@protoc_insertion_point(field_release:priemman.v1.OAuthCallbackResponse.session_token)
  return _impl_.session_token_.Release();
}
inline void OAuthCallbackResponse::set_allocated_session_token(std::string* session_token) {
  if (session_token != nullptr) {
    
  } else {
    
  }
  _impl_.session_token_.SetAllocated(session_token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_token_.IsDefault()) {
    _impl_.session_token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.OAuthCallbackResponse.session_token)
}

// bool is_new_user = 2;
inline void OAuthCallbackResponse::clear_is_new_user() {
  _impl_.is_new_user_ = false;
}
inline bool OAuthCallbackResponse::_internal_is_new_user() const {
  return _impl_.is_new_user_;
}
inline bool OAuthCallbackResponse::is_new_user() const {
  // @@protoc_insertion_point(field_get:priemman.v1.OAuthCallbackResponse.is_new_user)
  return _internal_is_new_user();
}
inline void OAuthCallbackResponse::_internal_set_is_new_user(bool value) {
  
  _impl_.is_new_user_ = value;
}
inline void OAuthCallbackResponse::set_is_new_user(bool value) {
  _internal_set_is_new_user(value);
  // @@protoc_insertion_point(field_set:priemman.v1.OAuthCallbackResponse.is_new_user)
}

// -------------------------------------------------------------------

// Session

// string token = 1;
inline void Session::clear_token() {
  _impl_.token_.ClearToEmpty();
}
inline const std::string& Session::token() const {
  // @@protoc_insertion_point(field_get:priemman.v1.Session.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Session::set_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.Session.token)
}
inline std::string* Session::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:priemman.v1.Session.token)
  return _s;
}
inline const std::string& Session::_internal_token() const {
  return _impl_.token_.Get();
}
inline void Session::_internal_set_token(const std::string& value) {
  
  _impl_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* Session::_internal_mutable_token() {
  
  return _impl_.token_.Mutable(GetArenaForAllocation());
}
inline std::string* Session::release_token() {
  // @@protoc_insertion_point(field_release:priemman.v1.Session.token)
  return _impl_.token_.Release();
}
inline void Session::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  _impl_.token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.Session.token)
}

// .priemman.v1.ObjectId user_id = 2;
inline bool Session::_internal_has_user_id() const {
  return this != internal_default_instance() && _impl_.user_id_ != nullptr;
}
inline bool Session::has_user_id() const {
  return _internal_has_user_id();
}
inline const ::priemman::v1::ObjectId& Session::_internal_user_id() const {
  const ::priemman::v1::ObjectId* p = _impl_.user_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::priemman::v1::ObjectId&>(
      ::priemman::v1::_ObjectId_default_instance_);
}
inline const ::priemman::v1::ObjectId& Session::user_id() const {
  // @@protoc_insertion_point(field_get:priemman.v1.Session.user_id)
  return _internal_user_id();
}
inline void Session::unsafe_arena_set_allocated_user_id(
    ::priemman::v1::ObjectId* user_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.user_id_);
  }
  _impl_.user_id_ = user_id;
  if (user_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:priemman.v1.Session.user_id)
}
inline ::priemman::v1::ObjectId* Session::release_user_id() {
  
  ::priemman::v1::ObjectId* temp = _impl_.user_id_;
  _impl_.user_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::priemman::v1::ObjectId* Session::unsafe_arena_release_user_id() {
  // @@protoc_insertion_point(field_release:priemman.v1.Session.user_id)
  
  ::priemman::v1::ObjectId* temp = _impl_.user_id_;
  _impl_.user_id_ = nullptr;
  return temp;
}
inline ::priemman::v1::ObjectId* Session::_internal_mutable_user_id() {
  
  if (_impl_.user_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::priemman::v1::ObjectId>(GetArenaForAllocation());
    _impl_.user_id_ = p;
  }
  return _impl_.user_id_;
}
inline ::priemman::v1::ObjectId* Session::mutable_user_id() {
  ::priemman::v1::ObjectId* _msg = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:priemman.v1.Session.user_id)
  return _msg;
}
inline void Session::set_allocated_user_id(::priemman::v1::ObjectId* user_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.user_id_);
  }
  if (user_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(user_id));
    if (message_arena != submessage_arena) {
      user_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, user_id, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.user_id_ = user_id;
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.Session.user_id)
}

// .google.protobuf.Timestamp expires_at = 3;
inline bool Session::_internal_has_expires_at() const {
  return this != internal_default_instance() && _impl_.expires_at_ != nullptr;
}
inline bool Session::has_expires_at() const {
  return _internal_has_expires_at();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Session::_internal_expires_at() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.expires_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& Session::expires_at() const {
  // @@protoc_insertion_point(field_get:priemman.v1.Session.expires_at)
  return _internal_expires_at();
}
inline void Session::unsafe_arena_set_allocated_expires_at(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* expires_at) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.expires_at_);
  }
  _impl_.expires_at_ = expires_at;
  if (expires_at) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:priemman.v1.Session.expires_at)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Session::release_expires_at() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.expires_at_;
  _impl_.expires_at_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Session::unsafe_arena_release_expires_at() {
  // @@protoc_insertion_point(field_release:priemman.v1.Session.expires_at)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.expires_at_;
  _impl_.expires_at_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Session::_internal_mutable_expires_at() {
  
  if (_impl_.expires_at_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.expires_at_ = p;
  }
  return _impl_.expires_at_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* Session::mutable_expires_at() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_expires_at();
  // @@protoc_insertion_point(field_mutable:priemman.v1.Session.expires_at)
  return _msg;
}
inline void Session::set_allocated_expires_at(::PROTOBUF_NAMESPACE_ID::Timestamp* expires_at) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.expires_at_);
  }
  if (expires_at) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(expires_at));
    if (message_arena != submessage_arena) {
      expires_at = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, expires_at, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.expires_at_ = expires_at;
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.Session.expires_at)
}

// -------------------------------------------------------------------

// LogoutRequest

// string session_token = 1;
inline void LogoutRequest::clear_session_token() {
  _impl_.session_token_.ClearToEmpty();
}
inline const std::string& LogoutRequest::session_token() const {
  // @@protoc_insertion_point(field_get:priemman.v1.LogoutRequest.session_token)
  return _internal_session_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LogoutRequest::set_session_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.session_token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:priemman.v1.LogoutRequest.session_token)
}
inline std::string* LogoutRequest::mutable_session_token() {
  std::string* _s = _internal_mutable_session_token();
  // @@protoc_insertion_point(field_mutable:priemman.v1.LogoutRequest.session_token)
  return _s;
}
inline const std::string& LogoutRequest::_internal_session_token() const {
  return _impl_.session_token_.Get();
}
inline void LogoutRequest::_internal_set_session_token(const std::string& value) {
  
  _impl_.session_token_.Set(value, GetArenaForAllocation());
}
inline std::string* LogoutRequest::_internal_mutable_session_token() {
  
  return _impl_.session_token_.Mutable(GetArenaForAllocation());
}
inline std::string* LogoutRequest::release_session_token() {
  // @@protoc_insertion_point(field_release:priemman.v1.LogoutRequest.session_token)
  return _impl_.session_token_.Release();
}
inline void LogoutRequest::set_allocated_session_token(std::string* session_token) {
  if (session_token != nullptr) {
    
  } else {
    
  }
  _impl_.session_token_.SetAllocated(session_token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.session_token_.IsDefault()) {
    _impl_.session_token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:priemman.v1.LogoutRequest.session_token)
}

// -------------------------------------------------------------------

// LogoutResponse

// bool success = 1;
inline void LogoutResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool LogoutResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool LogoutResponse::success() const {
  // @@protoc_insertion_point(field_get:priemman.v1.LogoutResponse.success)
  return _internal_success();
}
inline void LogoutResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void LogoutResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:priemman.v1.LogoutResponse.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace priemman

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::priemman::v1::AuthProvider> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::priemman::v1::AuthProvider>() {
  return ::priemman::v1::AuthProvider_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_auth_2eproto
